# NOTE: update this with your service name
service: aida-0-x-meta

# Create an optimized package for our functions
package:
  individually: true
  exclude:
    - ${self:provider.frontendDirectoryName}/node_modules/**
    - ${self:provider.frontendDirectoryName}/public/**
    - ${self:provider.frontendDirectoryName}/src/**
    - ${self:provider.frontendDirectoryName}/package.json
    - ${self:provider.frontendDirectoryName}/package-lock.json
    - ${self:provider.frontendDirectoryName}/README.md
    - node_modules/**
    - amplify/**
    - public/**
    - src/**
    - yarn.lock

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-output-to-env
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs14.x
  projectName: aida
  frontendDirectoryName: aidafront
  stage: develop
  region: us-east-1
  environment:
    PROJECT_NAME: ${self:provider.projectName}
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action: "cognito-idp:*"
      Resource: !Sub arn:aws:cognito-idp:${self:provider.region}:${AWS::AccountId}:userpool/${userPool}
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${DataTable}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${DataTable}/index/*
custom:
  outputToEnv:
    fileName: ../${self:provider.frontendDirectoryName}/.env
    map:
      REACT_APP_COGNITO_APP_CLIENT_ID: AppClientId
      REACT_APP_COGNITO_DOMAIN: CognitoDomain
      REACT_APP_COGNITO_REGION: Region
      REACT_APP_COGNITO_USER_POOL_ID: UserPoolID
      REACT_APP_API_URL: ServiceEndpoint
      REACT_APP_API_REDIRECT_URL: CloudFrontDistributionDomainName
  s3Sync:
    - bucketName: ${self:provider.projectName}-${self:provider.stage}-front
      localDir: ../${self:provider.frontendDirectoryName}/build/
      acl: public-read # optional

resources:
  # building cognito
  - ${file(cognitoUserPool.yml)}
  # building authorizer
  - ${file(apiGatewayAuthorizer.yml)}
  # table deployment dynamodb
  - ${file(table.yml)}
  # app deployment s3 bucket
  - ${file(appDeployment.yml)}

functions: ${file(api.yml)}

