export const constants = {
  TABLE_NAME_DATA_TABLE: "DataTable",
  ACTION_KEY: 'Action',
  DEFAULT_MESSAGE_UNAUTHORIZED_USER: "Unauthorized User",
  DATA_NOT_FOUND: "Data not found",
  DEVICE_DATA_NOT_FOUND: "Device data not found",
  COMPANY_DATA_NOT_FOUND: "Company data not found",
  CAMERA_DATA_NOT_FOUND: "Camera data not found",
  ACTION_CREATE: 'create',
  ACTION_UPDATE: 'update',
  USER_HASH: 'USR#',
  COMPANY_HASH: 'COM#',
  DEVICE_HASH: 'DEV#',
  CAMERA_HASH: 'CAM#',
  USER_KEYWORD: "user",
  COMPANY_KEYWORD: "company",
  CAMERA_KEYWORD: "camera",
  DEVICE_KEYWORD: "device",
  CAMERA_VISIBILITY_KEYWORD: "camera-visibility",
  LIMIT_20: 20,
  GLOBAL_INDEX_GSI1: "GSI1"
};